import React, { Component } from 'react'
import Box from '../components/common/Box'
import Columns from '../components/common/Columns'
import Footer from '../components/common/Footer'

export default class PageFooter extends Component {
  render () {
    return (
      <Footer>

          <Box direction="row" className="footerContainer" wrap={true} align="center">
            <Box direction="row"className="numberOne">
              <Columns >
                <div className="under"><img id="menuLogo" src="http://i.imgur.com/OlNC7UY.png" title="" /></div>
              </Columns>

              <Box direction="row" className="footer-grid flexy2" >
                <Box>
                  <div className="item footer-1">
                    <h6>VCAA NAPLAN Help
                    desk</h6>
                  </div>
                  <div className="item"><a href="">Freecall 1800 658 637</a></div>
                  <div className="item"><a href="">vcaa.naplan.help@edumail.vic.gov.au</a></div>
                </Box>

                <Columns>
                  <div className="item">
                    <h6>Privacy</h6>
                  </div>
                  <div className="item"><a href="">The VCAA is commited to the protection of student information generated by the NAPLAN 2016.
                  All personal information collected during NAPLAN is used in accordance with the Privacy and Data Protection Act 2014.</a>
                  </div>
                </Columns>
              </Box>
            </Box>

            <Box direction="row" className="colopon flexy3">
              <div className="column flexy4">
                <ul className="column list-inline flexy5" >
                  <li className="listy"><a href="">Privacy Policy</a></li>
                  <li className="listy"><a href="">Terms of Service</a></li>
                  <li className="listy"><span>© 2013-2016 VCAA®. All Rights Reserved.</span></li>
                </ul>
              </div>
            </Box>

          </Box>
      </Footer>
    )
  }
}
