export const OIDC_LOGOUT_SUCCESS = 'OIDC_LOGOUT_SUCCESS';
export const OIDC_LOAD_TOKEN_SUCCESS = 'OIDC_LOAD_TOKEN_SUCCESS';
export const OIDC_LOAD_TOKEN_ERROR = 'OIDC_LOAD_TOKEN_ERROR';

export const STORAGE_KEY = 'oidc.expired';
export const USER_EXPIRED = 'USER_EXPIRED';
export const REDIRECT_SUCCESS = 'REDIRECT_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const SILENT_RENEW_ERROR = 'SILENT_RENEW_ERROR';
export const SESSION_TERMINATED = 'SESSION_TERMINATED';
export const USER_EXPIRING = 'USER_EXPIRING';
export const USER_FOUND = 'USER_FOUND';

export const LOADING_USER = 'LOADING_USER';

export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
