export const LOAD_SUBSCRIPTIONS_START = 'LOAD_SUBSCRIPTIONS_START';
export const LOAD_SUBSCRIPTIONS_SUCCESS = 'LOAD_SUBSCRIPTIONS_SUCCESS';


export const STORAGE_KEY = 'oidc.expired';
export const USER_EXPIRED = 'USER_EXPIRED';
export const REDIRECT_SUCCESS = 'REDIRECT_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const SILENT_RENEW_ERROR = 'SILENT_RENEW_ERROR';
export const SESSION_TERMINATED = 'SESSION_TERMINATED';
export const USER_EXPIRING = 'USER_EXPIRING';
export const USER_FOUND = 'USER_FOUND';
export const LOADING_USER = 'LOADING_USER'
