export const OIDC_LOGOUT_SUCCESS = 'OIDC_LOGOUT_SUCCESS';
export const OIDC_LOAD_TOKEN_SUCCESS = 'OIDC_LOAD_TOKEN_SUCCESS';
export const OIDC_LOAD_TOKEN_ERROR = 'OIDC_LOAD_TOKEN_ERROR';
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const STORAGE_KEY = 'oidc.expired';
export const USER_EXPIRED = 'USER_EXPIRED';
export const REDIRECT_SUCCESS = 'REDIRECT_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const SILENT_RENEW_ERROR = 'SILENT_RENEW_ERROR';
export const SESSION_TERMINATED = 'SESSION_TERMINATED';
export const USER_EXPIRING = 'USER_EXPIRING';
export const USER_FOUND = 'USER_FOUND';
export const LOADING_USER = 'LOADING_USER';
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SCHOOL_DETAILS_SELECT = 'SCHOOL_DETAILS_SELECT';
export const SCHOOL_DETAILS_SUBMIT_SUCCESS = 'SCHOOL_DETAILS_SUBMIT_SUCCESS';
export const SCHOOL_DETAILS_FETCH_SUCCESS = 'SCHOOL_DETAILS_FETCH_SUCCESS';
export const SCHOOL_DETAILS_FETCH_FAILURE = 'STATEMENT_FETCH_FAILURE';
export const LOAD_SCHOOL_SEARCH = 'LOAD_SCHOOL_SEARCH';
export const SCHOOLSEARCH_FETCH = 'SCHOOLSEARCH_FETCH';
export const SCHOOLSEARCH_FETCH_SUCCESS = 'SCHOOLSEARCH_FETCH_SUCCESS';

//-- STATEMENT TYPES

//- Statment
//export const LOAD_STATEMENT_DETAILS = 'LOAD_STATEMENT_DETAILS'

//-- Statment Get
export const STATEMENT_FETCH = 'STATEMENT_FETCH'
export const STATEMENT_FETCH_SUCCESS = 'STATEMENT_FETCH_SUCCESS'
export const STATEMENT_FETCH_FAILURE = 'STATEMENT_FETCH_FAILURE'

//--
export const STATEMENT_SUBMIT = 'STATEMENT_SUBMIT'
export const STATEMENT_SUBMIT_SUCCESS = 'STATEMENT_SUBMIT_SUCCESS'
export const STATEMENT_SUBMIT_FAILURE = 'STATEMENT_SUBMIT_FAILURE'

//-- Manage Schools
export const MANAGESCHOOLSEARCH_FETCH = 'MANAGESCHOOLSEARCH_FETCH'
export const MANAGESCHOOLSEARCH_FETCH_SUCCESS = 'MANAGESCHOOLSEARCH_FETCH_SUCCESS'
export const MANAGESCHOOLSEARCH_FETCH_FAILURE = 'MANAGESCHOOLSEARCH_FETCH_FAILURE'

//--Get Schools
export const GETSCHOOL_FETCH = 'GETSCHOOL_FETCH'
export const GETSCHOOL_FETCH_SUCCESS = 'GETSCHOOL_FETCH_SUCCESS'
export const GETSCHOOL_FETCH_FAILURE = 'GETSCHOOL_FETCH_FAILURE'

export const SCHOOL_SUBMIT_SUCCESS = 'SCHOOL_SUBMIT_SUCCESS'
export const SCHOOL_SUBMIT_FAILURE = 'SCHOOL_SUBMIT_FAILURE'

//-- GET Sectors
export const GETSSECTORS_FETCH = 'GETSECTORS_FETCH'
export const GETSECTORS_FETCH_SUCCESS = 'GETSECTORS_FETCH_SUCCESS'
export const GETSECTORS_FETCH_FAILURE = 'GETSECTORS_FETCH_FAILURE'


//-- GET Suburbs
export const GETSUBURBS_FETCH = 'GETSUBURBS_FETCH'
export const GETSUBURBS_FETCH_SUCCESS = 'GETSUBURBS_FETCH_SUCCESS'
export const GETSUBURBS_FETCH_FAILURE = 'GETSUBURBS_FETCH_FAILURE'

export const USER_LOGGEDIN = 'USER_LOGGEDIN';
